// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Перевіряє email/пароль та повертає JWT токен і профіль користувача.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вхід користувача",
                "parameters": [
                    {
                        "description": "Дані для входу",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успішний вхід",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Невірні дані запиту",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Невірні облікові дані",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Користувач не активний",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Серверна помилка",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Створює новий акаунт користувача з email, username та паролем.\nПовертає JWT токен та профіль користувача.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Реєстрація нового користувача",
                "parameters": [
                    {
                        "description": "Дані для реєстрації",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Користувача створено",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Невірні дані запиту або бізнес-правила",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email або username вже зайняті",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Серверна помилка",
                        "schema": {
                            "$ref": "#/definitions/auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/friends": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Повертає список користувачів зі статусом accepted для поточного користувача.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Список друзів користувача",
                "responses": {
                    "200": {
                        "description": "Список друзів",
                        "schema": {
                            "$ref": "#/definitions/friends.FriendsListResponse"
                        }
                    },
                    "401": {
                        "description": "Неавторизовано",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутрішня помилка сервера",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/friends/requests": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Створює новий запит у друзі зі статусом pending.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Надіслати запит у друзі",
                "parameters": [
                    {
                        "description": "Цільовий користувач",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/friends.SendFriendRequestRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Запит надіслано",
                        "schema": {
                            "$ref": "#/definitions/friends.SendFriendRequestResponse"
                        }
                    },
                    "400": {
                        "description": "Невірні дані або спроба додати себе",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неавторизовано",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Користувача не знайдено",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Запит уже існує",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутрішня помилка сервера",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/friends/requests/respond": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Дозволяє отримувачу запиту прийняти або відхилити pending-запит.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Відповісти на запит у друзі",
                "parameters": [
                    {
                        "description": "Користувач-відправник і дія",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/friends.RespondFriendRequestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новий статус запиту",
                        "schema": {
                            "$ref": "#/definitions/friends.FriendRequestStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Невірні дані або дія",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неавторизовано",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Запит не знайдено",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Запит не в pending статусі",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутрішня помилка сервера",
                        "schema": {
                            "$ref": "#/definitions/friends.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/movies": {
            "get": {
                "description": "Повертає список фільмів з пагінацією.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movies"
                ],
                "summary": "Список фільмів",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Номер сторінки (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Ліміт на сторінку (default 20, max 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/movies.GetMoviesResponse"
                        }
                    },
                    "400": {
                        "description": "Некоректні query-параметри",
                        "schema": {
                            "$ref": "#/definitions/movies.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Помилка бази даних",
                        "schema": {
                            "$ref": "#/definitions/movies.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Повертає \"pong\" якщо сервіс працює.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Перевірка доступності сервісу",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PingResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Повертає профіль поточного авторизованого користувача.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Поточний профіль користувача",
                "responses": {
                    "200": {
                        "description": "Профіль користувача",
                        "schema": {
                            "$ref": "#/definitions/users.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Токен невалідний або користувача не знайдено",
                        "schema": {
                            "$ref": "#/definitions/users.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Користувач неактивний",
                        "schema": {
                            "$ref": "#/definitions/users.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутрішня помилка сервера",
                        "schema": {
                            "$ref": "#/definitions/users.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "secret123"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "secret123"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "friends.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "friends.FriendRequestStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "accepted"
                }
            }
        },
        "friends.FriendsListResponse": {
            "type": "object",
            "properties": {
                "friends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        },
        "friends.RespondFriendRequestRequest": {
            "type": "object",
            "required": [
                "action",
                "from_user_id"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "example": "accept"
                },
                "from_user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "friends.SendFriendRequestRequest": {
            "type": "object",
            "required": [
                "to_user_id"
            ],
            "properties": {
                "to_user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "friends.SendFriendRequestResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "main.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://cdn.example.com/avatars/johndoe.png"
                },
                "bio": {
                    "type": "string",
                    "example": "Book lover and sci-fi fan."
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "display_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                },
                "email_verified": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "last_login_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "movies.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid query parameters"
                }
            }
        },
        "movies.GetMoviesResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/movies.MovieItemResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "movies.MovieItemResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "release_year": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "users.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "unauthorized"
                }
            }
        },
        "users.MeResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Book Recommendation System API",
	Description:      "API для реєстрації, автентифікації та базових сервісів системи рекомендацій.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
