definitions:
  auth.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: secret123
        type: string
    required:
    - email
    - password
    type: object
  auth.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: secret123
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  title: Book Recommendation System API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Перевіряє email/пароль та повертає JWT токен
      parameters:
      - description: Дані для входу
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вхід користувача
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Створює новий акаунт користувача з email та паролем
      parameters:
      - description: Дані для реєстрації
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Реєстрація нового користувача
      tags:
      - auth
swagger: "2.0"
